//! SEC-001 Packet C-A/C-B/D — native command surface confinement.
//!
//! Exactly fourteen `privileged_auth` commands may ever be exposed to the
//! WebView, and nothing else from the module tree — no sign-arbitrary-bytes,
//! no pepper/DPAPI-blob/device-private-key getter, no raw Argon2 verifier
//! export, no arbitrary file read, no raw keyset-manifest-bytes command.
//! This is checked structurally against the actual shipped
//! `capabilities/default.json` and `src/privileged_auth/mod.rs`, so a future
//! change that adds an unauthorized command or a forbidden getter fails this test
//! even if nobody remembers to update a hand-maintained list.
//!
//! D-1B adds exactly one command, `native_attest_privileged_action`, and one
//! generated permission. It signs one frame shape over natively-derived fields;
//! the tests below prove it takes no caller-supplied bytes to sign, no path, no
//! wall clock, and no branch.

use std::fs;
use std::path::PathBuf;

const EXACT_FOURTEEN_COMMANDS: &[&str] = &[
    "native_import_device_enrollment_file",
    "native_generate_device_registration_proof",
    "native_finalize_device_enrollment",
    "native_complete_oac_provisioning",
    "native_argon2_benchmark",
    "native_get_device_registration_status",
    "native_verify_offline_pin",
    "native_clear_offline_lockout",
    "native_prepare_staff_session_challenge",
    "native_persist_staff_session_assertion",
    "native_clear_staff_session",
    "native_prepare_oac_reanchor_challenge",
    "native_persist_oac_reanchor",
    "native_attest_privileged_action",
];

const FORBIDDEN_NAME_FRAGMENTS: &[&str] = &[
    "sign_arbitrary",
    "sign_bytes",
    "sign_payload",
    "get_pepper",
    "get_dpapi",
    "dpapi_blob",
    "get_device_private_key",
    "device_private_key",
    "raw_argon2",
    "argon2_verifier",
    "read_file",
    "arbitrary_file",
    "keyset_manifest_bytes",
    "raw_keyset",
];

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn capabilities_json() -> serde_json::Value {
    let path = manifest_dir().join("capabilities").join("default.json");
    let raw =
        fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("cannot parse {}: {e}", path.display()))
}

fn granted_native_permissions() -> Vec<String> {
    let json = capabilities_json();
    let permissions = json["permissions"].as_array().expect("permissions array");
    permissions
        .iter()
        .filter_map(|p| p.as_str())
        .filter(|p| p.starts_with("allow-native-"))
        .map(|p| p.to_string())
        .collect()
}

fn mod_rs_source() -> String {
    let path = manifest_dir()
        .join("src")
        .join("privileged_auth")
        .join("mod.rs");
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
}

fn lib_rs_source() -> String {
    let path = manifest_dir().join("src").join("lib.rs");
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
}

#[test]
fn exactly_fourteen_native_commands_are_granted_in_capabilities() {
    let granted = granted_native_permissions();
    let mut expected: Vec<String> = EXACT_FOURTEEN_COMMANDS
        .iter()
        .map(|c| format!("allow-{}", c.replace('_', "-")))
        .collect();
    expected.sort();
    let mut actual = granted.clone();
    actual.sort();
    assert_eq!(
        actual, expected,
        "capabilities/default.json must grant exactly the fourteen frozen commands"
    );
}

#[test]
fn exactly_fourteen_tauri_command_functions_are_defined_in_mod_rs() {
    let source = mod_rs_source();
    let defined: Vec<&str> = EXACT_FOURTEEN_COMMANDS
        .iter()
        .filter(|name| source.contains(&format!("pub fn {name}(")))
        .copied()
        .collect();
    assert_eq!(
        defined.len(),
        14,
        "expected exactly 14 command functions defined, found: {defined:?}"
    );

    let command_attr_count = source.matches("#[tauri::command]").count();
    assert_eq!(
        command_attr_count, 14,
        "expected exactly 14 #[tauri::command]-annotated functions in mod.rs"
    );
}

#[test]
fn exactly_fourteen_commands_are_registered_in_generate_handler() {
    let source = lib_rs_source();
    for name in EXACT_FOURTEEN_COMMANDS {
        assert!(
            source.contains(&format!("privileged_auth::{name}")),
            "lib.rs generate_handler! must register privileged_auth::{name}"
        );
    }
    let registered = source.matches("privileged_auth::native_").count();
    assert_eq!(
        registered, 14,
        "generate_handler! must register exactly 14 privileged_auth commands"
    );
}

#[test]
fn exactly_one_new_d1b_generated_permission_exists() {
    let dir = manifest_dir().join("permissions").join("autogenerated");
    let mut names: Vec<String> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .filter_map(|e| e.file_name().into_string().ok())
        .filter(|n| n.starts_with("native_") && n.ends_with(".toml"))
        .collect();
    names.sort();
    assert_eq!(
        names.len(),
        EXACT_FOURTEEN_COMMANDS.len(),
        "one generated permission file per native command, no more: {names:?}"
    );
    assert!(names.contains(&"native_attest_privileged_action.toml".to_string()));

    let toml = fs::read_to_string(dir.join("native_attest_privileged_action.toml")).unwrap();
    assert!(toml.contains("identifier = \"allow-native-attest-privileged-action\""));
    assert!(toml.contains("commands.allow = [\"native_attest_privileged_action\"]"));
    assert!(toml.contains("identifier = \"deny-native-attest-privileged-action\""));
}

#[test]
fn native_attest_privileged_action_exposes_no_signing_path_or_clock_surface() {
    let source = mod_rs_source();
    let signature_block: Vec<&str> = source
        .lines()
        .skip_while(|line| {
            !line
                .trim_start()
                .starts_with("pub fn native_attest_privileged_action(")
        })
        .take_while(|line| !line.contains(')'))
        .collect();
    let combined = signature_block.join(" ");
    assert!(
        !combined.is_empty(),
        "native_attest_privileged_action signature must exist in mod.rs"
    );
    // No arbitrary-bytes signing surface, no caller-controlled path, no WebView
    // clock (Ruling R1), no WebView branch (Ruling R2).
    for forbidden in [
        "bytes",
        "payload",
        "message",
        "digest",
        "prefix",
        "preimage",
        "path",
        "file",
        "now_ms",
        "now:",
        "branch_id",
        "branchId",
        "key",
        "pepper",
    ] {
        assert!(
            !combined.contains(forbidden),
            "native_attest_privileged_action must not take a '{forbidden}' argument, found: {combined}"
        );
    }
    // Exactly the six declared arguments.
    for expected in [
        "manager_staff_id: String",
        "action_id: String",
        "target_order_id: String",
        "target_order_utc7_date: String",
        "local_intent_id: String",
        "pin: String",
    ] {
        assert!(
            combined.contains(expected),
            "missing declared argument {expected} in: {combined}"
        );
    }
}

#[test]
fn the_pin_is_never_persisted_logged_or_returned() {
    let attestation = fs::read_to_string(
        manifest_dir()
            .join("src")
            .join("privileged_auth")
            .join("action_attestation.rs"),
    )
    .expect("action_attestation.rs must exist");
    assert!(
        attestation.contains("pin.zeroize()"),
        "the owned PIN must be zeroized on every path"
    );
    for forbidden in ["println!", "eprintln!", "dbg!", "log::"] {
        assert!(
            !attestation.contains(forbidden),
            "action_attestation.rs must not log ({forbidden})"
        );
    }
    // The returned DTO carries no PIN-shaped field.
    let dto_block: String = attestation
        .lines()
        .skip_while(|l| !l.contains("pub struct PrivilegedActionAttestationDto"))
        .take_while(|l| !l.trim().eq("}"))
        .collect::<Vec<_>>()
        .join(" ");
    assert!(
        !dto_block.contains("pin"),
        "the attestation DTO must never expose the PIN: {dto_block}"
    );
}

#[test]
fn no_forbidden_command_name_fragment_appears_in_granted_permissions() {
    let granted = granted_native_permissions();
    for permission in &granted {
        for fragment in FORBIDDEN_NAME_FRAGMENTS {
            assert!(
                !permission.replace('-', "_").contains(fragment),
                "granted permission '{permission}' matches forbidden fragment '{fragment}'"
            );
        }
    }
}

#[test]
fn no_forbidden_public_tauri_command_exists_in_mod_rs() {
    let source = mod_rs_source();
    for line in source.lines() {
        if !line.trim_start().starts_with("pub fn ") {
            continue;
        }
        let lower = line.to_ascii_lowercase();
        for fragment in FORBIDDEN_NAME_FRAGMENTS {
            assert!(
                !lower.contains(fragment),
                "public function line matches a forbidden fragment: {line}"
            );
        }
    }
}

#[test]
fn native_import_device_enrollment_file_has_no_caller_controlled_path_argument() {
    let source = mod_rs_source();
    let signature_line = source
        .lines()
        .find(|line| {
            line.trim_start()
                .starts_with("pub fn native_import_device_enrollment_file(")
        })
        .expect("native_import_device_enrollment_file signature line must exist in mod.rs");
    assert!(
        signature_line.contains("native_import_device_enrollment_file()"),
        "native_import_device_enrollment_file must take zero WebView-supplied arguments \
         (no caller-controlled file path), found: {signature_line}"
    );
}

#[test]
fn native_verify_offline_pin_has_no_caller_controlled_time_or_branch_arguments() {
    let source = mod_rs_source();
    let signature_block: Vec<&str> = source
        .lines()
        .skip_while(|line| {
            !line
                .trim_start()
                .starts_with("pub fn native_verify_offline_pin(")
        })
        .take_while(|line| !line.contains('{'))
        .collect();
    let combined = signature_block.join(" ");
    assert!(
        !combined.contains("now_ms") && !combined.contains("now:"),
        "native_verify_offline_pin must NOT take WebView now_ms (Ruling R1), found: {combined}"
    );
    assert!(
        !combined.contains("branch_id") && !combined.contains("branchId"),
        "native_verify_offline_pin must NOT take WebView branch_id (Ruling R2), found: {combined}"
    );
}

#[test]
fn all_seventeen_privileged_auth_modules_are_declared() {
    let source = mod_rs_source();
    let expected_modules = [
        "action_attestation",
        "argon2_benchmark",
        "argon2_kdf",
        "clock_guard",
        "device_proof",
        "device_registration_proof",
        "dpapi_envelope",
        "enrollment_import",
        "enrollment_meta",
        "frames",
        "lockout_state",
        "monotonic_clock",
        "oac_keyset_frame",
        "offline_verifier",
        "pepper_store",
        "security_device_id",
        "staff_session",
    ];
    for module in expected_modules {
        assert!(
            source.contains(&format!("mod {module};")),
            "mod.rs must declare `pub mod {module};`"
        );
    }
}

/// SEC-001 epoch-2 native rollback remediation — exact persisted-store
/// version-envelope inventory. Each row names the file and the explicit
/// version constant it must declare; a future silent addition/removal of a
/// privileged-auth store's version marker fails this test, mirroring the
/// exhaustiveness style used for the fourteen-command surface above.
const EXPECTED_PRIVILEGED_AUTH_VERSION_MARKERS: &[(&str, &str)] = &[
    ("pepper_store.rs", "PEPPER_STORE_VERSION"),
    ("security_device_id.rs", "SECURITY_DEVICE_ID_STORE_VERSION"),
    ("device_proof.rs", "DEVICE_PROOF_KEY_STORE_VERSION"),
    ("enrollment_meta.rs", "STAGED_ENROLLMENT_SCHEMA_VERSION"),
    ("enrollment_meta.rs", "ENROLLMENT_FENCE_SCHEMA_VERSION"),
    ("lockout_state.rs", "LOCKOUT_STORE_SCHEMA_VERSION"),
    ("clock_guard.rs", "CLOCK_GUARD_SCHEMA_VERSION"),
];

#[test]
fn sec_001_epoch2_persisted_store_version_envelope_inventory_is_present() {
    for (file, marker) in EXPECTED_PRIVILEGED_AUTH_VERSION_MARKERS {
        let path = manifest_dir()
            .join("src")
            .join("privileged_auth")
            .join(file);
        let source = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        assert!(
            source.contains(&format!("pub const {marker}")),
            "{file} must declare an explicit version-envelope constant `{marker}` \
             (SEC-001 epoch-2 persisted-store inventory row missing)"
        );
    }
}

#[test]
fn sec_001_epoch2_global_compatibility_epoch_is_exactly_two() {
    let path = manifest_dir().join("src").join("epoch_floor.rs");
    let source =
        fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    assert!(
        source.contains("pub const MAX_KNOWN_EPOCH_SCHEMA: u32 = 2;"),
        "MAX_KNOWN_EPOCH_SCHEMA must be exactly 2 after the SEC-001 epoch-2 remediation"
    );
    assert!(
        source.contains("fn privileged_auth_state_exists("),
        "epoch_floor.rs must widen virgin/non-virgin detection to privileged-auth artifacts"
    );
}

#[test]
fn sec_001_epoch2_package_version_is_not_placeholder_in_either_manifest() {
    let tauri_conf_path = manifest_dir().join("tauri.conf.json");
    let tauri_conf = fs::read_to_string(&tauri_conf_path).unwrap();
    let tauri_json: serde_json::Value = serde_json::from_str(&tauri_conf).unwrap();
    let tauri_version = tauri_json["version"]
        .as_str()
        .expect("tauri.conf.json must have version");
    assert_ne!(tauri_version, "0.0.0");

    let cargo_toml_path = manifest_dir().join("Cargo.toml");
    let cargo_toml = fs::read_to_string(&cargo_toml_path).unwrap();
    let cargo_version = cargo_toml
        .lines()
        .find_map(|l| l.trim().strip_prefix("version = \""))
        .and_then(|rest| rest.strip_suffix('"'))
        .expect("Cargo.toml must have a version field");
    assert_eq!(
        cargo_version, tauri_version,
        "Cargo.toml and tauri.conf.json versions must stay synchronized"
    );
}
