import type { PosProduct } from './types';

/** Mock catalog aligned with reference HTML */
export const DEV_POS_PRODUCTS: PosProduct[] = [
  {
    id: 'p1',
    name: "Hill's Science Diet สุนัขสูงอายุ 7+ 5.67 kg",
    sku: 'HSD-567',
    barcode: '8850007890123',
    category: 'อาหารสัตว์',
    emoji: '🐕',
    imageUrl: null,
    stock: 98,
    baseUnit: 'ชิ้น',
    allowNegativeStock: true,
    tierPrices: { wholesale: 2200, vip: 2100, agent1: 2280 },
    uomOptions: [{ unit: 'ชิ้น', factor: 1, price: 2400 }],
  },
  {
    id: 'p2',
    name: 'Royal Canin Mini Indoor Senior 3 kg',
    sku: 'RC-MIS-3',
    barcode: '3182550789456',
    category: 'อาหารสัตว์',
    emoji: '🐩',
    imageUrl: null,
    stock: 96,
    baseUnit: 'ชิ้น',
    uomOptions: [{ unit: 'ชิ้น', factor: 1, price: 1029 }],
  },
  {
    id: 'p3',
    name: 'Maxima อาหารเปียก กระป๋อง 380 g',
    sku: 'MX-380',
    barcode: '8850001234567',
    category: 'อาหารสัตว์',
    emoji: '🥫',
    imageUrl: null,
    stock: 99,
    baseUnit: 'ชิ้น',
    tierPrices: { wholesale: 68, vip: 72 },
    uomOptions: [
      { unit: 'ชิ้น', factor: 1, price: 79 },
      { unit: 'แพ็ค', factor: 6, price: 450 },
      { unit: 'ลัง', factor: 24, price: 1700 },
    ],
  },
  {
    id: 'p4',
    name: 'Smart Heart อาหารลูกสุนัข เนื้อวัวนม 8 kg',
    sku: 'SH-PUP-8',
    barcode: '8850009876543',
    category: 'อาหารสัตว์',
    emoji: '🐶',
    imageUrl: null,
    stock: 99,
    baseUnit: 'ชิ้น',
    uomOptions: [{ unit: 'ชิ้น', factor: 1, price: 759 }],
  },
  {
    id: 'p5',
    name: 'Jerhigh ฮอทดอกบาร์ รสไก่ 150 g',
    sku: 'JH-150',
    barcode: '8858753012345',
    category: 'ทรีทและขนม',
    emoji: '🌭',
    imageUrl: null,
    stock: 99,
    baseUnit: 'ชิ้น',
    uomOptions: [
      { unit: 'ชิ้น', factor: 1, price: 45 },
      { unit: 'โหล', factor: 12, price: 510 },
      { unit: 'ลัง', factor: 48, price: 1900 },
    ],
  },
  {
    id: 'p6',
    name: 'Biscal ขนมคุกกี้สุนัข สูตรชีส 60 g',
    sku: 'BS-60',
    barcode: '8858753098765',
    category: 'ทรีทและขนม',
    emoji: '🍪',
    imageUrl: null,
    stock: 100,
    baseUnit: 'ชิ้น',
    uomOptions: [{ unit: 'ชิ้น', factor: 1, price: 197 }],
  },
  {
    id: 'p7',
    name: 'Pedigree เดนตาสติก พันธุ์เล็ก 210 g',
    sku: 'PD-210',
    barcode: '8850003456789',
    category: 'ทรีทและขนม',
    emoji: '🦷',
    imageUrl: null,
    stock: 100,
    baseUnit: 'ชิ้น',
    uomOptions: [{ unit: 'ชิ้น', factor: 1, price: 126 }],
  },
  {
    id: 'p8',
    name: 'Kaniva อาหารเม็ด รสแกะทูน่าข้าว 1.4 kg',
    sku: 'KN-14',
    barcode: '8858656001234',
    category: 'อาหารสัตว์',
    emoji: '🐱',
    imageUrl: null,
    stock: 100,
    baseUnit: 'ชิ้น',
    uomOptions: [{ unit: 'ชิ้น', factor: 1, price: 279 }],
  },
  {
    id: 'p9',
    name: 'Orijen สูตรแมวเด็กและแมวโต 1.8 kg',
    sku: 'OR-18',
    barcode: '7613287890123',
    category: 'อาหารสัตว์',
    emoji: '🐈',
    imageUrl: null,
    stock: 100,
    baseUnit: 'ชิ้น',
    uomOptions: [{ unit: 'ชิ้น', factor: 1, price: 1100 }],
  },
  {
    id: 'p10',
    name: 'Purina One ลูกแมวอายุ 3 สัปดาห์ 1.3 kg',
    sku: 'PO-13',
    barcode: '7613287890123',
    category: 'อาหารสัตว์',
    emoji: '🐟',
    imageUrl: null,
    stock: 99,
    baseUnit: 'ชิ้น',
    uomOptions: [{ unit: 'ชิ้น', factor: 1, price: 433 }],
  },
  {
    id: 'p11',
    name: 'Nekko อาหารเปียกลูกแมว 70 g',
    sku: 'NK-70',
    barcode: '8858636001234',
    category: 'อาหารสัตว์',
    emoji: '🦈',
    imageUrl: null,
    stock: 100,
    baseUnit: 'ชิ้น',
    uomOptions: [{ unit: 'ชิ้น', factor: 1, price: 23 }],
  },
  {
    id: 'p12',
    name: 'Royal Canin อาหารเปียกแมวโต 85 g',
    sku: 'RC-WET-85',
    barcode: '3182550789456',
    category: 'อาหารสัตว์',
    emoji: '🐾',
    imageUrl: null,
    stock: 100,
    baseUnit: 'ชิ้น',
    uomOptions: [{ unit: 'ชิ้น', factor: 1, price: 329 }],
  },
];

export const DEV_CATEGORY_GRADIENTS: Record<string, string> = {
  'อาหารสัตว์': 'linear-gradient(135deg,#1D9E75,#085041)',
  'ทรีทและขนม': 'linear-gradient(135deg,#BA7517,#633806)',
  'ของเล่น': 'linear-gradient(135deg,#D85A30,#993C1D)',
};
